### ISSUE TITLE
[FEAT] 캐릭터 선택창 UI 및 네비게이션 기능 구현

### ISSUE THREAD

**Issue by bom0320** [FourLeaves4/Client#4]
🎯 **목표**:

캐릭터 선택창에서 사용자가 캐릭터를 탐색하고 선택할 수 있는 **UI와 로직**을 구현합니다.

또한 "구글로 시작하기" 버튼 클릭 시, `Main` 네비게이터의 `Home` 탭으로 이동하는 **네비게이션 연결**을 구현합니다.

---

### **Tasks** ✅

- [x]  🖼️ **캐릭터 리스트를 기반으로 이미지와 설명 표시**
- [x]  ↔️ **화살표 버튼을 사용한 캐릭터 탐색 기능 추가**
- [x]  📝 **선택된 캐릭터 정보를 화면에 표시**
- [ ]  🔗 **"구글로 시작하기" 버튼을 통해 Home 탭으로 이동하는 네비게이션 연결**
- [x]  🎨 **스타일링 보완 (폰트, 버튼 크기, 배경 색 등)**

---

### **Acceptance Criteria** 🏁

- [ ]  🔄 사용자가 화살표 버튼을 눌러 캐릭터를 탐색할 수 있음
- [ ]  🖼️ 선택된 캐릭터의 이미지와 설명이 화면에 표시됨
- [ ]  🔗 "구글로 시작하기" 버튼 클릭 시 Home 탭으로 이동
- [ ]  🎨 UI 스타일이 디자인 요구사항에 부합함

**Comment by bom0320** [comment]
Git 클론 후, feature/Character-page/#12 이 브랜치로 전환해서 개발 진행해주세요.

**Comment by bom0320** [comment]
Git 클론 후, feature-CharacterPage-4 브랜치로 전환해서 개발 진행해주세요.
